build:
    environment:
        php:
            version: 7.0
    dependencies:
        before:
            - composer global require "fxp/composer-asset-plugin:~1.1.1"
    tests:
        override:
            -
                command: 'phpunit --coverage-clover=coverage.xml'
                coverage:
                    file: 'coverage.xml'
                    format: 'php-clover'

filter:
    excluded_paths:
        - 'tests/*'

checks:
    php: true

