build:
    environment:
        php:
            version: 7.2
    tests:
        override:
            -
                command: 'vendor/bin/phpunit --testsuite Unit --coverage-clover=coverage.xml'
                coverage:
                    file: 'coverage.xml'
                    format: 'php-clover'

filter:
    excluded_paths:
        - 'tests/*'

checks:
    php: true

