language: php
php:
  - '7.1'
  - '7.2'
  - '7.3'

env:
  matrix:
    - COMPOSER_OPTIONS="--prefer-lowest --prefer-stable"
    - COMPOSER_OPTIONS=""

install:
  - composer update $COMPOSER_OPTIONS

before_script:
  - composer setup-integration

script:
  - composer stan
  - composer unit
  - composer integration

after_script:
  - composer teardown-integration